    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-custom">
                <div class="panel-heading">
                    <a id="logo" href="<?php echo BASE; ?>">
                        <img class="img-responsive" src="<?php echo IMG; ?>hxphp-logo.png" alt="">
                    </a> <br>
                    <?php echo (isset($this->menu) ? $this->menu : ''); ?>
                </div>
                <div class="panel-body">
                    <?php 
                        $this->partial('message', array(
                            'msg' => 'Teste'
                        )); 
                    ?>

                <fieldset class="grupo">
                    <div class="campo">
                        <label for="name">
                            Nome
                        </label>
                        <input type="text" id="name" name="name" value="" />
                    </div>
                    <div class="campo">
                        <label for="Email">
                            Email
                        </label>
                        <input type="text" id="email" name="Email" required="" />
                    </div>
                </fieldset>
                <div class="campo">
                    <label for="nome">
                        Nome
                    </label>
                    <input type="text" id="nome" name="nome" style="width: 23em" value="<?php echo $nome?>"
                    required/>
                </div>










                    <p>
                        Agora acesse a <a class="btn btn-success btn-xs" href="http://www.hxtutors.com.br/curso/dominando-o-hxphp-framework/" title="Acesse o curso completo sobre HXPHP" target="_blank">área de membros</a> e assista ao nosso curso oficial para dominar completamente esta poderosa ferramenta.
                    </p>
                </div>
            </div>
        </div>
    </div>