    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-custom">
                <div class="panel-heading">
                    <a id="logo" href="<?php echo BASE; ?>">
                        <img class="img-responsive" src="<?php echo IMG; ?>" alt="">
                    </a>

                </div>

                <div class="panel-body">

                    <?php echo (isset($this->alert) ? $this->alert :  ''); ?>
                    <form class="form-horizontal" action="<?php echo BASE; ?>cadastro/cadastrar" method="post">
                      <div class="form-group">
                        <label for="name" class="col-sm-2 control-label">Nome</label>
                        <div class="col-sm-10">
                          <input required type="name" class="form-control" id="name" name="name" placeholder="Nome completo" value="<?php echo $this->request->post('name') ?>">
                        </div>
                      </div>

                      <div class="form-group">
                        <label for="email" class="col-sm-2 control-label">Email</label>
                        <div class="col-sm-10">
                          <input required type="email" class="form-control" id="email" name="email" placeholder="Email" value="<?php echo $this->request->post('email') ?>" >
                        </div>
                      </div>
                      
                      <div class="form-group">
                        <label for="username" class="col-sm-2 control-label">Usuário</label>
                        <div class="col-sm-10">
                          <input required type="username" class="form-control" id="username" name="username" placeholder="Usuário" value="<?php echo $this->request->post('username') ?>">
                        </div>
                      </div>
                      
                      <div class="form-group">
                        <label for="password" class="col-sm-2 control-label">Senha</label>
                        <div class="col-sm-10">
                          <input required type="password" class="form-control" id="password" name="password" placeholder="Senha" value="<?php echo $this->request->post('password') ?>">
                        </div>
                      </div>
                      <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                          <button type="submit" class="btn btn-default">Cadastrar</button>
                        </div>
                      </div>
                    </form>

                </div>
            </div>
        </div>
    </div>