    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-custom">
                <div class="panel-heading">
                    <a id="logo" href="<?php echo BASE; ?>">
                        <img class="img-responsive" src="<?php echo IMG; ?>" alt="">
                    </a>
                </div>
                <div class="panel-body">

                    <form class="form-horizontal">
                      <div class="alert alert-block alert-warning">
                        <h4>
                        Recupere sua senha.
                        </h4>
                        Será enviado um link de redefinição de senha para seu email.
                      </div>            
                      <div class="form-group">
                        <label for="username" class="col-sm-2 control-label">Usuário</label>
                        <div class="col-sm-10">
                          <input type="username" class="form-control" id="username" name="username" placeholder="Usuário">
                        </div>
                      </div>

                      <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                          <button type="submit" class="btn btn-success">Enviar link de redefinição</button>
                        </div>
                      </div>
                    </form>
                </div>
            </div>
        </div>
    </div>