    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-custom">
                <div class="panel-heading">
                    <a id="logo" href="<?php echo BASE; ?>">
                        <img class="img-responsive" src="<?php echo IMG; ?>" alt="">
                    </a>
                </div>
                <div class="panel-body">
                    <?php echo (isset($this->alert) ? $this->alert : ''); ?>
                    <form class="form-horizontal" action="<?php echo BASE; ?>recuperar/alterar/<?php echo $view_token ?>" method="post">
                      <div class="form-group">
                        <label for="password" class="col-sm-2 control-label">Nova senha</label>
                        <div class="col-sm-10">
                          <input type="password" class="form-control" id="password" name="password" placeholder="Informe sua nova senha">
                        </div>
                      </div>
                      <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                          <button type="submit" class="btn btn-success">Alterar minha senha</button>
                        </div>
                      </div>
                    </form>
                </div>
            </div>
        </div>
    </div>