    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-custom">
                <div class="panel-heading">
                    <a id="logo" href="<?php echo BASE; ?>">
                        <img class="img-responsive" src="<?php echo IMG; ?>" alt="">
                    </a> <br>
                    <?php echo (isset($this->menu) ? $this->menu : ''); ?>
                </div>
                <div class="panel-body">
                    <!--
                    ** LINKS
                    -->
                    <a class="btn btn-success btn-xs" href="cadastro" title="cadastro">Cadastro</a>
                    <a class="btn btn-success btn-xs" href="login" title="login">Login</a>
                    <a class="btn btn-success btn-xs" href="recuperar" title="recuperar">Recuperar a senha</a>
                </div>
            </div>
        </div>
    </div>
