    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-custom">
                <div class="panel-heading">
                    <a id="logo" href="<?php echo BASE; ?>">
                        <img class="img-responsive" src="<?php echo IMG; ?>" alt="">
                    </a>
                </div>
                <div class="panel-body">
                   
                <h1 class="alert alert-sucess">
                Bem vindo ao sistema7tech
                </h1>
                <h2>
                Usuário logado: 
                <?php
                  echo $view_user->name;
                ?>
                </h2>
                <a href="<?php echo BASE . 'login/sair'; ?>" class="btn btn-danger">Sair</a>
                </div>
            </div>
        </div>
    </div>